### ISSUE TITLE
Translate Rice GbDoc into Chinese

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-gb#2]
Set `lang` to `zh`, `script` to `Hans` (which is the default), all autofilled terms must be in Chinese too.

**Comment by opoudjis** [comment]
I'm assuming this is going to end up as separate header files (for the different document types) including a common body.

**Comment by ronaldtse** [comment]
I'm going to get the content translated as well, so the resulting documents will be purely in English / Chinese.

**Comment by ronaldtse** [comment]
I've just done it with 1d77c4a, however I can't seem to compile the document. @opoudjis could you help check? Thanks!

And yes, we should use separate header files with a common body (en body vs zh body).

**Comment by ronaldtse** [comment]
P.S. I've split the files to use separate header files with common body includes in b56a6a6.

**Comment by opoudjis** [comment]
A note is in the `<dl>`, and isodoc isn't dealing with it. Need to make it deal.

**Comment by opoudjis** [comment]
Fixed in isodoc
