### ISSUE TITLE
[metanorma] Error: loading gem `metanorma-gb` failed. Exiting.

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn-samples-gb#38]
@ronaldtse should we do something about this https://github.com/metanorma/metanorma-cli/blob/master/metanorma-cli.gemspec#L42 ?

**Comment by opoudjis** [comment]
We have deprecated this gem and stopped development on it. IMO, it should stay disabled, and so should this repo.

**Comment by CAMOBAP** [comment]
@opoudjis thanks for info
