### ISSUE TITLE
Migrate Travis to GitHub Actions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-gb#5]
@CAMOBAP795 can you please help fix this? https://github.com/metanorma/mn-samples-gb/blob/master/.github/workflows/main.yml

**Comment by ronaldtse** [comment]
We can use the Metanorma docker container to directly compile too!

**Comment by ronaldtse** [comment]
And remove AppVeyor once done.

**Comment by opoudjis** [comment]
... And out in place MacOS, Ubuntu, Windows workflows in common with the other samples repositories.

**Comment by CAMOBAP** [comment]
Done
